# Linear Regression

In [19]:
import torch

## Basic elements

### Define data

In [20]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[4], [5], [6]])

### Hypothesis

In [21]:
W = torch.zeros(1, requires_grad=True) # requires_grad = 학습대상
b = torch.zeros(1, requires_grad=True)
hypothesis = x_train * W + b

In [22]:
print(W, b)

tensor([0.], requires_grad=True) tensor([0.], requires_grad=True)


### Loss function: MSE

In [23]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(25.6667, grad_fn=<MeanBackward1>)


### Gradient descent

In [24]:
optimizer = torch.optim.SGD([W, b], lr=0.01)

""" 항상 붙어다니는 3줄 """
optimizer.zero_grad() # Gradient 초기화
cost.backward()       # Gradient 계산
optimizer.step()      # Gradient 방향대로 이동함

## 2.Full training code

In [25]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = torch.optim.SGD([W, b], lr=0.01)

nb_epochs = 2000
for epoch in range(1, nb_epochs + 1):
    hypothesis = x_train * W + b
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    optimizer.zero_grad() 
    cost.backward()       
    optimizer.step()      

In [27]:
print(W, b)

tensor([1.9974], requires_grad=True) tensor([0.0060], requires_grad=True)


In [29]:
x_train * W + b

tensor([[2.0034],
        [4.0007],
        [5.9981]], grad_fn=<AddBackward0>)