## Import 

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

## Softmax

Convert numbers to probabilities with softmax

\begin{align}
P(class = i) = \frac{e^i}{ \sum{e^i}}
\end{align}

\begin{eqnarray}
P(class = 1) = \frac{e^1}{ e^1 + e^2 + e^3} \\
P(class = 2) = \frac{e^2}{ e^1 + e^2 + e^3} \\
P(class = 3) = \frac{e^3}{ e^1 + e^2 + e^3}
\end{eqnarray}

In [3]:
z = torch.FloatTensor([1, 2, 3])

PyTorch has a softmax function 

In [4]:
hypothesis = F.softmax(z, dim=0)
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


Since they are probabilities, they should add up to 1

In [5]:
hypothesis.sum()

tensor(1.)

## Cross Entropy Loss (Low-level)

For multi-class classification, we use the cross entropy loss

\begin{align}
L = \frac{1}{N} \sum{-y} \log{(y')}
\end{align}

where $\ y' $ is the predicted probability and $\ y $ is the correct probability (0 or 1)

In [6]:
z = torch.rand(3, 5, requires_grad=True) # 5 : # of class / 3 :  # of sample
hypothesis = F.softmax(z, dim=1)
print(z)
print(hypothesis) ## prediction

tensor([[0.7576, 0.2793, 0.4031, 0.7347, 0.0293],
        [0.7999, 0.3971, 0.7544, 0.5695, 0.4388],
        [0.6387, 0.5247, 0.6826, 0.3051, 0.4635]], requires_grad=True)
tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward>)


In [7]:
y = torch.randint(5, (3,)).long() # 5 : the highest integer / (3, ) : matrix dimension
print(y) ## make label

tensor([0, 2, 1])


※ Scatter Example : scatter_(dim, index, src) → Tensor

```
>>> x = torch.rand(2, 5)
>>> x
tensor([[ 0.3992,  0.2908,  0.9044,  0.4850,  0.6004],
        [ 0.5735,  0.9006,  0.6797,  0.4152,  0.1732]])
>>> torch.zeros(3, 5).scatter_(0,
        torch.tensor([[0, 1, 2, 0, 0],        # x 메트릭스가 zeros 메트릭스에 뿌려질 인덱스를 표현함
                      [2, 0, 0, 1, 2]]), x)
    
tensor([[ 0.3992,  0.9006,  0.6797,  0.4850,  0.6004],
        [ 0.0000,  0.2908,  0.0000,  0.4152,  0.0000],
        [ 0.5735,  0.0000,  0.9044,  0.0000,  0.1732]])

>>> z = torch.zeros(2, 4).scatter_(1, torch.tensor([[2], [3]]), 1.23)
>>> z
tensor([[ 0.0000,  0.0000,  1.2300,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  1.2300]])
```

In [8]:
y_one_hot = torch.zeros_like(hypothesis)
y_one_hot.scatter_(1, y.unsqueeze(1), 1) # dim = 1, index = [[0], [2], [1]], src = 1

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])

※ 참고자료 : https://ratsgo.github.io/deep%20learning/2017/10/02/softmax/

In [9]:
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()
print(cost)

tensor(1.4689, grad_fn=<MeanBackward1>)


## Cross Entropy Loss with torch.nn.functional

In [10]:
# Low level
torch.log(F.softmax(z, dim=1))

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]], grad_fn=<LogBackward>)

In [11]:
# High level
F.log_softmax(z, dim=1)

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]],
       grad_fn=<LogSoftmaxBackward>)

In [12]:
# Higher level
F.nll_loss(F.log_softmax(z, dim=1), y) # Negative Log Likelihood

tensor(1.4689, grad_fn=<NllLossBackward>)

In [13]:
# The highest level
F.cross_entropy(z, y)

tensor(1.4689, grad_fn=<NllLossBackward>)

## Training a prediction model

In [14]:
x_train = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0]

x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

In [15]:
# 변수 초기화
W = torch.zeros((4, 3), requires_grad=True)
b = torch.zeros(3, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.1)

nb_epochs = 1000
for epoch in range(nb_epochs+1):
    
    # Cost 계산
    hypothesis = F.softmax(x_train.matmul(W) + b, dim=1)
    y_one_hot = torch.zeros_like(hypothesis)
    y_one_hot.scatter_(1, y_train.unsqueeze(1), 1)
    cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()
    
    # H(x)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost {:.6f}'.format(
            epoch, nb_epochs, cost.item()))

Epoch    0/1000 Cost 1.098612
Epoch  100/1000 Cost 0.704199
Epoch  200/1000 Cost 0.622999
Epoch  300/1000 Cost 0.565717
Epoch  400/1000 Cost 0.515291
Epoch  500/1000 Cost 0.467662
Epoch  600/1000 Cost 0.421278
Epoch  700/1000 Cost 0.375401
Epoch  800/1000 Cost 0.329766
Epoch  900/1000 Cost 0.285072
Epoch 1000/1000 Cost 0.248155


## High-level Implementation with nn.Module

In [16]:
class SoftmaxClassifierModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(4, 3)
        
    def forward(self, x):
        return self.linear(x)
    
model = SoftmaxClassifierModel()

In [17]:
optimizer = optim.SGD(model.parameters(), lr=0.1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    prediction = model(x_train)
    cost = F.cross_entropy(prediction, y_train) # scatter 생략
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost {:.6f}'.format(
            epoch, nb_epochs, cost.item()))

# < prediction 결과 >
# tensor([[-4.0293,  0.1455,  5.0992],
#         [-2.7892,  0.4444,  2.3614],
#         [-6.9309,  3.2734,  4.3893],
#         [-5.9871,  3.4495,  2.2823],
#         [ 0.5029,  0.9579, -2.4000],
#         [ 1.2916,  2.6939, -5.9512],
#         [ 2.3026,  1.4373, -5.6941],
#         [ 3.5098,  1.6711, -7.7266]], grad_fn=<AddmmBackward>)

Epoch    0/1000 Cost 1.849513
Epoch  100/1000 Cost 0.689894
Epoch  200/1000 Cost 0.609259
Epoch  300/1000 Cost 0.551218
Epoch  400/1000 Cost 0.500141
Epoch  500/1000 Cost 0.451947
Epoch  600/1000 Cost 0.405051
Epoch  700/1000 Cost 0.358733
Epoch  800/1000 Cost 0.312912
Epoch  900/1000 Cost 0.269521
Epoch 1000/1000 Cost 0.241922


## Test 

In [29]:
class SoftmaxClassifierModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 3)
        
    def forward(self, x):
        return self.linear(x)

In [30]:
x_train = torch.FloatTensor([[1, 2, 1],
                             [1, 3, 2],
                             [1, 3, 4],
                             [1, 5, 5],
                             [1, 7, 5],
                             [1, 2, 5],
                             [1, 6, 6],
                             [1, 7, 7]])
y_train = torch.LongTensor([2, 2, 2, 1, 1, 1, 0, 0])

x_test = torch.FloatTensor([[2, 1, 1], [3, 1, 2], [3, 3, 4]])
y_test = torch.LongTensor([2, 2, 2])

In [46]:
model = SoftmaxClassifierModel()
optimizer = optim.SGD(model.parameters(), lr=0.1)
nb_epochs = 1000

In [47]:
def train(model, optimizer, nb_epochs, x_train, y_train):
    
    for epoch in range(nb_epochs):
        
        prediction = model(x_train)
        cost = F.cross_entropy(prediction, y_train)
               
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        
        if epoch % 100 == 0:
            print('Epoch {:4d}/{} Cost {:.6f}'.format(epoch, nb_epochs, cost.item()))
        

def test(model, optimizer, x_test, y_test):
    
    prediction = model(x_test)
    predicted_classes = prediction.max(1)[1]
    correct_count = (predicted_classes == y_test).sum().item()
    cost = F.cross_entropy(prediction, y_test)

    print('Accuracy {}% Cost {:.6f}'.format(correct_count / len(y_test) * 100, cost.item()))

In [48]:
train(model, optimizer, nb_epochs, x_train, y_train)

Epoch    0/1000 Cost 1.786065
Epoch  100/1000 Cost 0.684155
Epoch  200/1000 Cost 0.587587
Epoch  300/1000 Cost 0.532195
Epoch  400/1000 Cost 0.492596
Epoch  500/1000 Cost 0.461466
Epoch  600/1000 Cost 0.435785
Epoch  700/1000 Cost 0.413983
Epoch  800/1000 Cost 0.395113
Epoch  900/1000 Cost 0.378543


In [49]:
test(model, optimizer, x_test, y_test)

Accuracy 100.0% Cost 0.000230
